# Generated by Django 5.1.5 on 2025-01-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_order_item_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
