# Generated by Django 5.1.5 on 2025-01-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='videos_uploaded/thumbnails/'),
        ),
    ]
