# Generated by Django 5.1.5 on 2025-01-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
